SET DEFINE OFF

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 1, 50, 4250);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 1, 30, 4250);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 1, 15, 4795);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 1, 50, 4795);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 1, 50, 7304);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 1, 50, 7304);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 2, 100, 5865);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 2, 60, 5865);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 1, 30, 8229);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 2, 100, 8229);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 3, 90, 2139);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 4, 120, 2139);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (3, 1, 50, 2139);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 2, 100, 8823);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 2, 100, 8823);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (3, 4, 120, 8823);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 1, 15, 7322);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 2, 100, 7322);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (3, 1, 50, 7322);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 3, 150, 4195);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 4, 200, 4195);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (3, 2, 30, 4195);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 1, 50, 7626);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 1, 30, 7626);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (3, 1, 50, 7626);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (4, 1, 15, 7626);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 2, 30, 2487);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 2, 60, 2487);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (3, 2, 60, 2487);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (4, 2, 100, 2487);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 1, 15, 1231);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 1, 50, 1231);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (3, 2, 100, 1231);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (4, 1, 30, 1231);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (1, 3, 150, 5774);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (2, 3, 90, 5774);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (3, 2, 60, 5774);

INSERT INTO FAKTURA_DANE (NR_POZYCJI, ILOSC_EGZEMPLARZY, CENA_WYPOZYCZENIA, NR_FAKTURY) 
VALUES (4, 3, 150, 5774);

