SET DEFINE OFF

INSERT INTO KONTO (LOGIN, HASLO, PLATFORMA, KOD_PRACOWNIKA) 
VALUES ('A.Bocianowska.o', 'ab123', 'Office365', 21);

INSERT INTO KONTO (LOGIN, HASLO, PLATFORMA, KOD_PRACOWNIKA) 
VALUES ('D.Wojciechowski.o', 'dwo123', 'Office365', 15);

INSERT INTO KONTO (LOGIN, HASLO, PLATFORMA, KOD_PRACOWNIKA) 
VALUES ('D.Wojciechowski.v', 'dwv456', 'Visual_studio', 15);

INSERT INTO KONTO (LOGIN, HASLO, PLATFORMA, KOD_PRACOWNIKA) 
VALUES ('A.Nowak.m', 'anm123', 'Mapy.cz', 18);

INSERT INTO KONTO (LOGIN, HASLO, PLATFORMA, KOD_PRACOWNIKA) 
VALUES ('J.Pudelkowski.m', 'jpm123', 'Mapy.cz', 26);

