SET DEFINE OFF

INSERT INTO OBOWIAZKI (ZAKRES_DZIALAN, WYNAGRODZENIE) 
VALUES ('Ksiegowy', 60);

INSERT INTO OBOWIAZKI (ZAKRES_DZIALAN, WYNAGRODZENIE) 
VALUES ('Informatyk', 50);

INSERT INTO OBOWIAZKI (ZAKRES_DZIALAN, WYNAGRODZENIE) 
VALUES ('Przewodnik', 35);

INSERT INTO OBOWIAZKI (ZAKRES_DZIALAN, WYNAGRODZENIE) 
VALUES ('Praca_przy_sprzecie', 25);

