SET DEFINE OFF

INSERT INTO PRACOWNIK (KOD_PRACOWNIKA, IMIE, NAZWISKO, LICZBA_GODZIN_PRACY, DATA_ROZPOCZECIA) 
VALUES (21, 'Alicja', 'Bocianowska', 240, to_date('12.06.2018', 'DD.MM.YYYY'));

INSERT INTO PRACOWNIK (KOD_PRACOWNIKA, IMIE, NAZWISKO, LICZBA_GODZIN_PRACY, DATA_ROZPOCZECIA) 
VALUES (15, 'Dawid', 'Wojciechowski', 168, to_date('24.03.2017', 'DD.MM.YYYY'));

INSERT INTO PRACOWNIK (KOD_PRACOWNIKA, IMIE, NAZWISKO, LICZBA_GODZIN_PRACY, DATA_ROZPOCZECIA) 
VALUES (13, 'Igor', 'Dunajec', 192, to_date('30.01.2017', 'DD.MM.YYYY'));

INSERT INTO PRACOWNIK (KOD_PRACOWNIKA, IMIE, NAZWISKO, LICZBA_GODZIN_PRACY, DATA_ROZPOCZECIA) 
VALUES (18, 'Agata', 'Nowak', 192, to_date('02.02.2018', 'DD.MM.YYYY'));

INSERT INTO PRACOWNIK (KOD_PRACOWNIKA, IMIE, NAZWISKO, LICZBA_GODZIN_PRACY, DATA_ROZPOCZECIA) 
VALUES (26, 'Jakub', 'Pudelkowski', 240, to_date('21.11.2017', 'DD.MM.YYYY'));

