SET DEFINE OFF

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (68912, 'Kask', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (94135, 'Plecak', 30);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (82775, 'Narty', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (85295, 'Okulary', 15);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (40274, 'Czekan', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (85404, 'Plecak', 30);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (64429, 'Narty', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA, DATA_OSTATNIEJ_NAPRAWY) 
VALUES (99010, 'Kijki', 30, to_date('16.02.2019', 'DD.MM.YYYY'));

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (95860, 'Okulary', 15);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (28458, 'Kask', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (92923, 'Kijki', 30);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (41143, 'Czekan', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (71389, 'Narty', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (88869, 'Okulary', 15);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (41939, 'Raki', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (87502, 'Okulary', 15);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (69266, 'Kask', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (48366, 'Czekan', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (41363, 'Okulary', 15);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA, DATA_OSTATNIEJ_NAPRAWY) 
VALUES (23631, 'Narty', 50, to_date('24.01.2019', 'DD.MM.YYYY'));

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (42609, 'Raki', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (14708, 'Czekan', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (67676, 'Plecak', 30);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (86515, 'Narty', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (64171, 'Raki', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (69630, 'Kijki', 30);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (15771, 'Kask', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (46051, 'Raki', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA, DATA_OSTATNIEJ_NAPRAWY) 
VALUES (73349, 'Plecak', 30, to_date('07.03.2019', 'DD.MM.YYYY'));

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (35572, 'Kask', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (95833, 'Kijki', 30);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (15819, 'Raki', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (96792, 'Kijki', 30);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA) 
VALUES (55753, 'Czekan', 50);

INSERT INTO SPRZET (NR_EGZEMPLARZA, NAZWA_SPRZETU, CENA, DATA_OSTATNIEJ_NAPRAWY) 
VALUES (75568, 'Plecak', 30, to_date('18.02.2019', 'DD.MM.YYYY'));

