SET DEFINE OFF

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (6, 'srednia', 2, 'Kuznice', 18, 'Dolina koscieliska', 240, 3, 3133);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (6, 'latwa', 2, 'Dolina koscieliska', 18, 'Droga Pod Reglami', 240, 2, 8229);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (7, 'trudna', 2, 'Kuznice', 26, 'Kuznice', 280, 1, 1183);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (7, 'latwa', 2, 'Droga Pod Reglami', 26, 'Kuznice', 280, 2, 7626);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (14, 'srednia', 4, 'Kuznice', 18, 'Kuznice', 560, 2, 5865);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (7, 'latwa', 2, 'Lysa Polana', 18, 'Palenica Bialczanska', 280, 5, 8823);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (14, 'srednia', 4, 'Kuznice', 26, 'Lysa Polana', 560, 2, 2487);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (11, 'trudna', 3, 'Kuznice', 18, 'Kuznice', 440, 1, 6666);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (11, 'latwa', 3, 'Dolina koscieliska', 26, 'Dolina koscieliska', 440, 5, 2139);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (14, 'latwa', 4, 'Kuznice', 18, 'Lysa Polana', 560, 2, 7322);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (10, 'latwa', 3, 'Palenica Bialczanska', 26, 'Droga Pod Reglami', 400, 4, 4195);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (15, 'srednia', 5, 'Kuznice', 18, 'Palenica Bialczanska', 600, 1, 1207);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (9, 'trudna', 3, 'Dolina koscieliska', 26, 'Dolina koscieliska', 360, 4, 4795);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (7, 'srednia', 2, 'Lysa Polana', 26, 'Palenica Bialczanska', 280, 1, 7304);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (5, 'latwa', 1, 'Kuznice', 26, 'Kuznice', 200, 5, 1052);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (15, 'latwa', 5, 'Palenica Bialczanska', 18, 'Kuznice', 600, 2, 1231);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (5, 'srednia', 1, 'Lysa Polana', 26, 'Lysa Polana', 200, 2, 4250);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (9, 'latwa', 3, 'Palenica Bialczanska', 26, 'Palenica Białczańska', 360, 2, 9540);

INSERT INTO WYCIECZKA (DLUGOSC_TRASY, TRUDNOSC, CZAS_PRZEJSCIA, POCZOTEK, KOD_PRACOWNIKA, KONIEC, CENA_WYCIECZKI, ILOSC_UCZESTNIKOW, NR_FAKTURY) 
VALUES (12, 'srednia', 4, 'Droga Pod Reglami', 18, 'Lysa Polana', 480, 3, 5774);

