SET DEFINE OFF

INSERT INTO ZAKRES_OBOWIAZKOW (KOD_PRACOWNIKA, ZAKRES_DZIALAN) 
VALUES (21, 'Ksiegowy');

INSERT INTO ZAKRES_OBOWIAZKOW (KOD_PRACOWNIKA, ZAKRES_DZIALAN) 
VALUES (15, 'Informatyk');

INSERT INTO ZAKRES_OBOWIAZKOW (KOD_PRACOWNIKA, ZAKRES_DZIALAN) 
VALUES (18, 'Przewodnik');

INSERT INTO ZAKRES_OBOWIAZKOW (KOD_PRACOWNIKA, ZAKRES_DZIALAN) 
VALUES (26, 'Przewodnik');

INSERT INTO ZAKRES_OBOWIAZKOW (KOD_PRACOWNIKA, ZAKRES_DZIALAN) 
VALUES (18, 'Praca_przy_sprzecie');

INSERT INTO ZAKRES_OBOWIAZKOW (KOD_PRACOWNIKA, ZAKRES_DZIALAN) 
VALUES (13, 'Praca_przy_sprzecie');

